# Generated by Django 5.1.4 on 2024-12-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('idpercent', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'db_table': 'percent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idproducts', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('descriprions', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('idregister', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('n_quantite', models.IntegerField(blank=True, null=True)),
                ('n_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.products')),
            ],
            options={
                'db_table': 'register',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('idprofit', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('n_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('idregister', models.ForeignKey(db_column='idregister', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.register')),
            ],
            options={
                'db_table': 'profit',
                'managed': True,
            },
        ),
    ]
